FROM nvidia/cuda

MAINTAINER Dejun Teng<tengdj@gmail.com>
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ \
	USER=root
	
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      openjdk-8-jdk \
      net-tools \
      curl \
      netcat \
      gnupg \
      apt-utils \
      gcc g++ cmake libboost-all-dev libgeos++-dev freeglut3-dev libcgal-dev software-properties-common wget git 

# install eigen
RUN wget http://bitbucket.org/eigen/eigen/get/3.3.7.tar.bz2 && \
    tar xvf 3.3.7.tar.bz2 && \
    mv eigen-eigen-323c052e1731/Eigen /usr/local/include && \
    rm -rf eigen-eigen-323c052e1731 && \
    rm 3.3.7.tar.bz2

# install MPFR
RUN wget https://www.mpfr.org/mpfr-current/mpfr-4.0.2.tar.xz && \
    tar xvf mpfr-4.0.2.tar.xz && \
    cd mpfr-4.0.2/ && \
    ./configure --prefix=/usr/local/ && \
    make -j20 && \
    make install && \
    cd ../ && \
    rm -rf mpfr-4.0.2*

# install spatialindex
RUN wget http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz && \
    tar zxvf spatialindex-src-1.8.5.tar.gz && \
    cd spatialindex-src-1.8.5 && \
    ./configure --prefix=/usr/local && \
    make -j20 && \
    make install && \
    cd ../ && \
    rm -rf spatialindex*


